query Event($eventId: Float!) {
  event(eventId: $eventId) {
    EventID
    title
    description
    locationTitle
    locationAddress
    imageUrl
    price
    category
    date
    startAt
    endAt
    position {
      lat
      lng
    }
    followers {
      UserID
    }
    users {
      UserID
      PhotoUrl
    }
    author {
      UserID
      Email
      Username
      PhotoUrl
      type
    }
  }
}
