query GetBillConditions($condition: String!) {
  getBillConditions(condition: $condition) {
    BillID
    createAt
    updateAt
    price
    status
    eventBuy {
      EventID
      imageUrl
      title
      startAt
      endAt
    }
  }
}
