query GetEventConditions($condition: String!) {
  getEventConditions(condition: $condition) {
    EventID
    title
    description
    locationTitle
    locationAddress
    imageUrl
    price
    category
    date
    startAt
    endAt
    createAt
    updateAt
  }
}
