query getUserId($userId: Float!) {
  getUserId(userId: $userId) {
    UserID
    Username
    Email
    PhotoUrl
    about
    followings {
      UserID
      PhotoUrl
      Username
      Email
    }
    followers {
      UserID
      PhotoUrl
      Username
      Email
    }
    interests {
      CategoryID
      title
      label
      color
    }
    bills {
      BillID
      createAt
      updateAt
      price
      status
      eventBuy {
        EventID
        imageUrl
        title
        startAt
        endAt
      }
    }
  }
}
